class AddFieldsToUsers < ActiveRecord::Migration[5.1]
  def change
    add_column :users, :bio, :text
    add_column :users, :Favourite_Destinations, :text
    add_column :users, :wish, :text
    add_column :users, :believes, :text
    add_column :users, :Friends_with_benefits, :text
    add_column :users, :passions, :text
    add_column :users, :Favourite_Quote, :text
    add_column :users, :why_are_you_on_earth, :text
    add_column :users, :Core_Values, :text
    add_column :users, :strengths, :text
    add_column :users, :Leadership_Styles, :text
    add_column :users, :Native_Language, :text
    add_column :users, :Business_Ventures, :text
    add_column :users, :Allergies, :text
    add_column :users, :Favourite_Time_of_sleep, :text
    add_column :users, :Favourite_Books, :text
    add_column :users, :Favourite_Movies, :text
    add_column :users, :school_type, :text
    add_column :users, :Relationship_status, :text
    add_column :users, :Favourite_Footwears, :text
    add_column :users, :Favourite_Brand, :text
    add_column :users, :Favourite_Pet, :text
    add_column :users, :Favourite_Seasons, :text
    add_column :users, :Favourite_Animals, :text
    add_column :users, :Favourite_University, :text
    add_column :users, :Favourite_Schools, :text
    add_column :users, :Favourite_Youtubers, :text
    add_column :users, :Favourite_Songs, :text
    add_column :users, :Favourite_Car, :text
    add_column :users, :Favourite_Countries, :text
    add_column :users, :Favourite_Basketball_Players, :text
    add_column :users, :Favourite_Food, :text
    add_column :users, :Best_Friends, :text
    add_column :users, :Favourite_Roommate, :text
    add_column :users, :Favourite_Professors, :text
    add_column :users, :Favourite_Teachers, :text
    add_column :users, :Favourite_Subjects, :text
    add_column :users, :Favourite_Footballers, :text
    add_column :users, :Favourite_TVshows, :text
    add_column :users, :Favourite_Sports, :text
    add_column :users, :Role_Model, :text
    add_column :users, :Voluntering_Work, :text
    add_column :users, :Experiences, :text
    add_column :users, :Profession, :text
    add_column :users, :School_Name, :text
    add_column :users, :Accomplishments, :text
    add_column :users, :Skills, :text
    add_column :users, :Goals, :text
    add_column :users, :Website, :string
    add_column :users, :Likes, :text
    add_column :users, :Interests, :text
    add_column :users, :Hobies, :text
    add_column :users, :phone_number, :text
    add_column :users, :dob, :text
    add_column :users, :Majors, :text
    add_column :users, :Minors, :text
    add_column :users, :sex, :string, null: false, default: 'male'
  end 
end
